server:
  port: 80
#禁用eureka
ribbon:
  eureka:
   enabled: false
#脱离eureka地址
microcloud-provider-dept:
  ribbon:
    listOfServers: http://dept-8001:8001,http://dept-8002:8002,http://dept-8003:8003
   