server:
  port: 80
eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    #fetch-registry: false     # 不通过eureka获取注册信息
    service-url:
      defaultZone: http://edmin:citydojava@eureka-7001:7001/eureka,http://edmin:citydojava@eureka-7002:7002/eureka,http://edmin:citydojava@eureka-7003:7003/eureka
#负载均衡也可以通过配置      
#ribbon: 
  #NFLoadBalancerRuleClassName:com.netflix.loadbalancer.WeightedResponseTimeRule      